-- MySQL Script generated by MySQL Workbench
-- 2020年10月22日 星期四 14时31分49秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_dingding
-- -----------------------------------------------------
-- 仿钉钉项目数据库

-- -----------------------------------------------------
-- Schema db_dingding
--
-- 仿钉钉项目数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dingding` DEFAULT CHARACTER SET utf8 ;
USE `db_dingding` ;

-- -----------------------------------------------------
-- Table `db_dingding`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `email` VARCHAR(200) NULL COMMENT '邮箱',
  `password` VARCHAR(200) NULL COMMENT '密码（密文）',
  `nickname` VARCHAR(80) NULL COMMENT '昵称',
  `status` INT NULL COMMENT '标志位 0 未激活，1激活',
  `icon` VARCHAR(255) NULL COMMENT '头像',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `db_dingding`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL COMMENT '用户id',
  `d_name` VARCHAR(200) NULL COMMENT '文档名',
  `d_address` VARCHAR(200) NULL COMMENT '文档地址',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '文档表';


-- -----------------------------------------------------
-- Table `db_dingding`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '组id',
  `u_id` INT NULL COMMENT '用户id',
  `g_name` VARCHAR(200) NULL COMMENT '组名',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '群';


-- -----------------------------------------------------
-- Table `db_dingding`.`sign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`sign` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `sp_id` INT NULL COMMENT '打卡计划id',
  `u_id` INT NULL COMMENT '打卡人id',
  `sign_time` DATETIME NULL COMMENT '打卡时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '打卡表';


-- -----------------------------------------------------
-- Table `db_dingding`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`organization` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '组织id',
  `u_id` INT NULL COMMENT '创建者id\n',
  `o_name` VARCHAR(200) NULL COMMENT '组织名',
  `o_address` VARCHAR(200) NULL COMMENT '组织地址',
  `o_description` VARCHAR(200) NULL COMMENT '组织描述',
  `createtime` DATE NULL COMMENT '创建时间',
  `updatetime` DATE NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '组织表';


-- -----------------------------------------------------
-- Table `db_dingding`.`sign_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`sign_plan` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `g_id` INT NULL COMMENT '群id',
  `u_id` INT NULL COMMENT '用户id(创建者)',
  `sp_name` VARCHAR(200) NULL COMMENT '打卡计划名',
  `start_time` TIME NULL COMMENT '打开卡开始时间',
  `end_time` TIME NULL COMMENT '结束时间',
  `start_date` DATE NULL COMMENT '打卡开始日期',
  `end_date` DATE NULL COMMENT '打卡结束日期',
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '打卡计划表';


-- -----------------------------------------------------
-- Table `db_dingding`.`group_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dingding`.`group_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `g_id` INT NULL COMMENT '群id',
  `u_id` INT NULL COMMENT '用户id',
  `createtime` DATETIME NULL COMMENT '入群时间\n',
  `status` INT NULL COMMENT '状态(0申请，-1未通过，1正常，2退出群)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '群_用户中间表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
